version: "3.7"

services:
  eti-micro-01-app:
    image: laravel-app
    build:
      args:
        user: eti-micro
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: eti-micro-01-app
    restart: unless-stopped
    depends_on:
      - eti-micro-01-server
      - eti-micro-01-db
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - eti-micro-01-network

  eti-micro-01-server:
    image: nginx:alpine
    container_name: eti-micro-01-server
    restart: unless-stopped
    ports:
      - 8000:80
      - 443:443
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - eti-micro-01-network

  eti-micro-01-db:
    image: mysql:5.7
    container_name: eti-micro-01-db
    restart: unless-stopped
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - eti-micro-01-network

networks:
  eti-micro-01-network:
    driver: bridge
